#!/usr/bin/perl -w
#
use Math::Trig;

sub log2 { log( $_[0] ) / log( 2 ) }

sub f2c  { ($_[0] - 32.0) * 5.0/9.0 }
sub c2f  { $_[0] * 9.0/5.0 + 32     }

sub p2k  { $_[0] * 0.4535924 }
sub k2p  { $_[0] / 0.4535924 }
sub o2g  { p2k($_[0]/16.0) * 1000.0 }
sub g2o  { k2p($_[0]/1000.0) * 16.0 }
sub i2m  { $_[0] * 0.0254 }
sub m2i  { $_[0] / 0.0254 }
sub bmi  { $_[0] / ($_[1]*$_[1]) }

sub sum  { my $s = 0.0; for(@_) { $s += $_; } return $s; }

my $expr = join( " ", @ARGV );
my $val  = eval( $expr );
printf "%d      %0.30f  0x%x  0b%b\n", $val, $val, $val, $val;
