#!/usr/bin/perl
use strict;
use warnings;

@ARGV == 1 or die "usage : enc <file>\n";
my $file = shift @ARGV;

system( "openssl aes-256-cbc -salt -in ${file} -out ${file}.enc" ) == 0 or die "ERROR: encryption failed\n";
