#!/usr/bin/env python3
#
import sys
import subprocess

cmd_en = True

def die( msg ):
    print( f'ERROR: {msg}' )
    sys.exit( 1 )

def cmd( c, echo=True, echo_stdout=False, can_die=True ):  
    if echo: print( c )
    if cmd_en:
        info = subprocess.run( c, shell=True, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT )
        if echo_stdout: print( info.stdout )
        if can_die and info.returncode != 0: die( f'command failed: {c}' )
        return info.stdout
    else:
        return ''

if len(sys.argv) != 2: die( 'usage : encrypt <file>' )
file = sys.argv[1]

cmd( f'gpg --symmetric --cipher-algo aes256 --no-symkey-cache --output {file}.gpg {file}' )
