#!/usr/bin/perl
use strict;
use warnings;
sub cmd { my $c = shift; print "${c}\n"; system( $c ) == 0 or die "ERROR: command failed: ${c}\n"; }

@ARGV >= 2 || die "usage: ftar my_tar file1 file2 ...\n";
my $archive = shift @ARGV;
my $files = join( " ", @ARGV );

$archive =~ /\.tar.gz$/ or $archive .= ".tar.gz";

cmd( "tar cfv - ${files} | pigz > ${archive}" );
exit 0;
