#!/usr/bin/perl
#
use strict;
use warnings;

my $dir       = `cat ~/.default_tree`;
my $recipient = `cat ~/.default_recipient`;

chdir( "$ENV{HOME}/backups" );
my $file = "${recipient}.tar.gz";
my $gpg_file = "${file}.gpg";
-d $dir or die "ERROR: $dir does not exist\n";
system( "tar cvfz ${file} $dir" ) == 0 or die "ERROR: tar failed\n";
print "Encrypting $file using -r ${recipient}...\n";
system( "gpg --encrypt -r ${recipient} ${file}" ) == 0 or die "ERROR: encryption failed\n";
print "Deleting ${file}...\n";
system( "rm -f $file" ) == 0 or die "ERROR: rm of $file failed\n";
print "Moving ${gpg_file} to /tmp...\n";
system( "mv ${gpg_file} /tmp/${gpg_file}; chmod 777 /tmp/${gpg_file}" ) == 0 or die "ERROR: could not copy ${gpg_file} to /tmp\n";
