#!/usr/bin/perl
#
use strict;
use warnings FATAL => 'all';

my $USER = "balfieri";

sub fatal ($) { die "ERROR: " . shift . "\n" }
sub cmd   ($) { my $c = shift; system( $c ) == 0 or fatal "cmd failed: $c" }

system( "mkdir -p /Volumes/apps" );
system( "mount_smbfs //${USER}\@mis1.nvidia.com/apps /Volumes/apps" );
