#!/usr/bin/perl
#
use strict;
use warnings;

my $dir       = `cat ~/.default_tree`;
my $recipient = `cat ~/.default_recipient`;

# common code to move somewhere else
#
chdir( "~" );
-d $dir and die "ERROR: ${dir} exists already, not going to overwrite it\n";
my $gpg_file = `ls ./backups/${recipient}*.gpg | tail -1`; chomp $gpg_file;
$gpg_file ne "" or die "ERROR: no backup file to restore\n";
my $file = $gpg_file;
$file =~ s/\.gpg$//;

print "Restoring from $gpg_file...\n";
system( "gpg --decrypt $gpg_file > $file" ) == 0 or die "ERROR: could not decrypt $gpg_file\n";
system( "tar xvfz ${file}" ) == 0 or die "ERROR: could not untar $file\n";
print "Deleting ${file}...\n";
system( "rm -f ${file}" );
