#!/usr/bin/env python3
#
import sys

start_price  = 23.00
start_mktcap = 678.88 * start_price/27.49
start_year   = 2023
growth_rate  = 1.07      # quarterly
year_cnt     = 10
share_cnt    = 1000      # placeholder for private number

use_canned_prices = True
canned_prices = [ 30,  40,  50,  60,  70,  80,  90, 
                 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 
                 200, 210, 220, 230, 240, 250, 260, 270, 280, 290,
                 300, 350, 400, 450, 500, 1000]
date_price_hit = {
  30:  '2023/05',
  40:  '2023/05',
  50:  '2023/08', 
  60:  '2024/01',
  70:  '2024/02', 
  80:  '2024/02',
  90:  '2024/03',
  100: '2024/05',
  110: '2024/05',
  120: '2024/06',
  130: '2024/06',
  140: '2024/06',
  150: '2025/02',
  160: '2025/07',
  170: '2025/07',
  180: '2025/07',
  190: '2025/10',
  200: '2025/10',
  210: '2025/10',
}

def die( msg ):
    print( f'ERROR: {msg}' )
    sys.exit( 1 )

i = 1
while i < len(sys.argv):
    arg = sys.argv[i]
    i += 1
    if   arg == '-growth_rate':
        growth_rate = float(sys.argv[i])
        i += 1
    elif arg == '-c' or arg == '-share_cnt':
        share_cnt = int(sys.argv[i])
        i += 1
    elif arg == '-use_canned_prices':
        use_canned_prices = int(sys.argv[i]) != 0
        i += 1
    else:
        die( f'unknown option: {arg}' )

gain = 1.0

if use_canned_prices:
    for price in canned_prices:
        mktcap = int(start_mktcap * price/start_price)
        valueM = (share_cnt * price) / 1000000.0
        date_hit = date_price_hit[price] if price in date_price_hit else ''
        print( f'{price:5d}  {mktcap:5d}  {valueM:7.2f}     {date_hit:7s}' )
else:
    for y in range(year_cnt+1):
        year  = start_year + y
        price = int(start_price * gain)
        mktcap = int(start_mktcap * gain)
        valueM = (share_cnt * price) / 1000000.0
        print( f'{year:4d} {gain:7.2f}  {price:5d}  {mktcap:5d}  {valueM:7.2f}' )
        for q in range(4): gain *= growth_rate
