#!/usr/bin/env python3
#
import sys

start_price  = 230
start_mktcap = 678.88 * 230/274.85
start_year   = 2023
growth_rate  = 1.07      # quarterly
year_cnt     = 10
share_cnt    = 1000      # placeholder for private number

use_canned_prices = True
canned_prices = [300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 10000]
date_price_hit = {
  300:  '2023/05',
  400:  '2023/05',
  500:  '2023/08', 
  600:  '2024/01',
  700:  '2024/02', 
  800:  '2024/02',
  900:  '2024/03',
  1000: '2024/05',
}

def die( msg ):
    print( f'ERROR: {msg}' )
    sys.exit( 1 )

i = 1
while i < len(sys.argv):
    arg = sys.argv[i]
    i += 1
    if   arg == '-growth_rate':
        growth_rate = float(sys.argv[i])
        i += 1
    elif arg == '-c' or arg == '-share_cnt':
        share_cnt = int(sys.argv[i])
        i += 1
    elif arg == '-use_canned_prices':
        use_canned_prices = int(sys.argv[i]) != 0
        i += 1
    else:
        die( f'unknown option: {arg}' )

gain = 1.0

if use_canned_prices:
    for price in canned_prices:
        mktcap = int(start_mktcap * price/start_price)
        valueM = (share_cnt * price) / 1000000.0
        date_hit = date_price_hit[price] if price in date_price_hit else ''
        print( f'{price:5d}  {mktcap:5d}  {valueM:7.2f}     {date_hit:7s}' )
else:
    for y in range(year_cnt+1):
        year  = start_year + y
        price = int(start_price * gain)
        mktcap = int(start_mktcap * gain)
        valueM = (share_cnt * price) / 1000000.0
        print( f'{year:4d} {gain:7.2f}  {price:5d}  {mktcap:5d}  {valueM:7.2f}' )
        for q in range(4): gain *= growth_rate
