#!/usr/bin/env python3
#
# prenotami - continually check appointment availability on prenotami.esteri.it
#
import os
import requests
from bs4 import BeautifulSoup

login_url = 'https://prenotami.esteri.it'
login_data = {
    'Email':    os.getenv( 'PRENOTAMI_USERNAME' ),
    'Password': os.getenv( 'PRENOTAMI_PASSWORD' )
}

session = requests.Session()

# go to main login page
response = session.get( login_url )
response.raise_for_status()
soup = BeautifulSoup( response.text, 'html.parser' )

# fill in Email/Password fields and submit
login_form = soup.find( 'form' )
action_url = login_url + login_form['action']
response = session.post( action_url, data=login_data )  
# it hangs, perhaps "click" on forward button instead?
response.raise_for_status()
soup = BeautifulSoup( response.text, 'html.parser' )

print( soup.prettify() )
