#!/usr/bin/env python3
#
# prenotami - continually check appointment availability on prenotami.esteri.it
#
import os
import requests
from bs4 import BeautifulSoup

login_url = 'https://prenotami.esteri.it'
login_data = {
    'username': os.getenv( 'PRENOTAMI_USERNAME' ),
    'password': os.getenv( 'PRENOTAMI_PASSWORD' )
}

session = requests.Session()

response = session.get( login_url )
print( response.text )

soup = BeautifulSoup( response.text, 'html.parser' )

links = soup.find_all('a')
for link in links:
    print( link.get('href') )

#response = session.post( login_url, data=login_data )
#print( response.text )

# make other requests
